# Generated by Django 3.0.4 on 2020-03-15 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
