# Generated by Django 3.0.4 on 2020-03-15 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200315_1617'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
