# Generated by Django 3.0.4 on 2020-03-15 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_comments_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
