# Generated by Django 3.0.4 on 2020-03-18 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_roles',
        ),
    ]
