# Generated by Django 3.0.4 on 2020-03-19 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_delete_user_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neededitems',
            name='prepartion',
        ),
        migrations.CreateModel(
            name='PreparationList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neededitems', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.NeededItems')),
                ('prepartion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Preparation')),
            ],
        ),
    ]
