# Generated by Django 3.0.4 on 2020-03-19 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20200319_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neededitems',
            old_name='item',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='preparation',
            old_name='title',
            new_name='name',
        ),
    ]
