# Generated by Django 3.0.4 on 2020-03-19 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20200319_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preparationlist',
            name='neededitems',
        ),
        migrations.RemoveField(
            model_name='preparationlist',
            name='prepartion',
        ),
        migrations.DeleteModel(
            name='NeededItems',
        ),
        migrations.DeleteModel(
            name='Preparation',
        ),
        migrations.DeleteModel(
            name='PreparationList',
        ),
    ]
