# Generated by Django 3.0.4 on 2020-03-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20200319_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeededItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('recommendationAddress', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Preparation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('needItems', models.ManyToManyField(to='home.NeededItems')),
            ],
        ),
    ]
