# Generated by Django 3.0.4 on 2020-03-19 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_neededitems_preparation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preparation',
            name='needItems',
        ),
        migrations.AddField(
            model_name='preparation',
            name='needItems',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.NeededItems'),
            preserve_default=False,
        ),
    ]
